/*
 * Meal Orders API
 *
 * Meal Orders management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package ambulance_project

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type AmbulancesAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateAmbulance - Saves new ambulance definition
   CreateAmbulance(ctx *gin.Context)

    // DeleteAmbulance - Deletes specific ambulance
   DeleteAmbulance(ctx *gin.Context)

    // GetAllAmbulances - Retrieves all ambulances
   GetAllAmbulances(ctx *gin.Context)

    // GetAmbulance - Get specific ambulance
   GetAmbulance(ctx *gin.Context)

 }

 // partial implementation of AmbulancesAPI - all functions must be implemented in add on files
type implAmbulancesAPI struct {

}

func newAmbulancesAPI() AmbulancesAPI {
  return &implAmbulancesAPI{}
}

func (this *implAmbulancesAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/ambulance", this.CreateAmbulance)
  routerGroup.Handle( http.MethodDelete, "/ambulance/:ambulanceId", this.DeleteAmbulance)
  routerGroup.Handle( http.MethodGet, "/ambulance", this.GetAllAmbulances)
  routerGroup.Handle( http.MethodGet, "/ambulance/:ambulanceId", this.GetAmbulance)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateAmbulance - Saves new ambulance definition
// func (this *implAmbulancesAPI) CreateAmbulance(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteAmbulance - Deletes specific ambulance
// func (this *implAmbulancesAPI) DeleteAmbulance(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetAllAmbulances - Retrieves all ambulances
// func (this *implAmbulancesAPI) GetAllAmbulances(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetAmbulance - Get specific ambulance
// func (this *implAmbulancesAPI) GetAmbulance(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

