/*
 * Meal Orders API
 *
 * Meal Orders management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package ambulance_project

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type MealOrdersAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateMealOrder - Creates a new meal order
   CreateMealOrder(ctx *gin.Context)

    // DeleteMealOrder - Deletes a specific meal order
   DeleteMealOrder(ctx *gin.Context)

    // GetMealOrder - Provides details about a specific meal order
   GetMealOrder(ctx *gin.Context)

    // GetMealOrders - Provides the list of meal orders
   GetMealOrders(ctx *gin.Context)

    // UpdateMealOrder - Updates a specific meal order
   UpdateMealOrder(ctx *gin.Context)

 }

 // partial implementation of MealOrdersAPI - all functions must be implemented in add on files
type implMealOrdersAPI struct {

}

func newMealOrdersAPI() MealOrdersAPI {
  return &implMealOrdersAPI{}
}

func (this *implMealOrdersAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/meal-orders/:ambulanceId/records", this.CreateMealOrder)
  routerGroup.Handle( http.MethodDelete, "/meal-orders/:ambulanceId/records/:orderId", this.DeleteMealOrder)
  routerGroup.Handle( http.MethodGet, "/meal-orders/:ambulanceId/records/:orderId", this.GetMealOrder)
  routerGroup.Handle( http.MethodGet, "/meal-orders/:ambulanceId/records", this.GetMealOrders)
  routerGroup.Handle( http.MethodPut, "/meal-orders/:ambulanceId/records/:orderId", this.UpdateMealOrder)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateMealOrder - Creates a new meal order
// func (this *implMealOrdersAPI) CreateMealOrder(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteMealOrder - Deletes a specific meal order
// func (this *implMealOrdersAPI) DeleteMealOrder(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetMealOrder - Provides details about a specific meal order
// func (this *implMealOrdersAPI) GetMealOrder(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetMealOrders - Provides the list of meal orders
// func (this *implMealOrdersAPI) GetMealOrders(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateMealOrder - Updates a specific meal order
// func (this *implMealOrdersAPI) UpdateMealOrder(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

