/*
 * Meal Orders API
 *
 * Meal Orders management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_project

import (
	"time"
)

type MealOrder struct {

	// Unique ID of the meal order
	Id string `json:"id"`

	// Name of the person ordering the meal
	Name string `json:"name"`

	// Dietary requirements of the person
	DietaryReq string `json:"dietaryReq"`

	// Medical needs related to the meal order
	MedicalNeed string `json:"medicalNeed"`

	// Time when the meal is to be consumed
	ConsumationTime time.Time `json:"consumationTime"`
}
